version: "3.8"

services:
  app:
    build: .
    container_name: user_crud_app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://host.docker.internal:27017/user_crud_db
    restart: unless-stopped
    networks:
      - app-network

  network:
    app-network:
      driver: bridge
